### ISSUE TITLE
Send Tweet without dialog 

### ISSUE THREAD

**Issue by fluidkarmadesigns** [jpurcell/birdhouse#21]
Is it possible to use Birdhouse to send a tweet without the dialog popup?

**Comment by jpurcell** [comment]
Yes it is, the send_tweet() function will do so. However, in order to access the function outside the BirdHouse object you will need to add a line of code:

<pre>
this.send_tweet = send_tweet;
</pre>


At line 1141. Then you ought to be able to call,

<pre>
BH.send_tweet("status="+escape( TWEET_STRING ),function(retval){
    if (retval===false) {
        // sending tweet failed
    } else {
        // sending tweet succeeded!
    }
});
</pre>


I hope that does it!

**Comment by fluidkarmadesigns** [comment]
That did it. Thanks

**Comment by lrkirven** [comment]
I keep getting a false response and my tweet never goes though.  Any ideas on debugging this?
