### ISSUE TITLE
Accented characters

### ISSUE THREAD

**Issue by pcalves** [jpurcell/birdhouse#22]
First of all, thanks for developing this plugin, it's a godsend!

That said (of course there's a "but"), I've also encountered a pretty big roadblock. Every time I try to send a tweet with accented characters (such as á, à, ã and so on...), Titanium returns the following error:

``` javascript
[WARN] Exception in event callback. {

    line = 121;

    message = "URI error";

    name = URIError;

    sourceId = 192571648;

    sourceURL = "file://localhost/Users/pc/mobile_BACKUP/AppSpot/Resources/scripts/twitter/lib/oauth.js";

}
```

I don't know how much inside your "jurisdiction" this is, seeing as the issue definitely lies within the oauth.js file, but still, if you could even shed some light into what could be causing this error, I'd pretty much love you forever!

**Comment by jpurcell** [comment]
Hey, I'm glad you find this useful!

That is a great question, and I am quite sure the issue is with character encoding, but I'm not sure where the problem is. On line 669 the tweet is being percent encoded:

<pre>
...escape(tweet.value)...
</pre>


Perhaps change the escape() function to encodeURI(). I am not well versed with character encodings and such, but here is a reference I found just now as I was searching for solutions:

http://www.javascripter.net/faq/accentedcharacters.htm

I hope that works!

**Comment by pcalves** [comment]
Well! That was incredibly simple. I just changed the escape to a encodeURIComponent and it started working perfectly. :D Thanks a lot for the prompt reply!

The question remains of why exactly it was freaking out before, but I'll get deep into character encodings only when I have no other choice. For now, hooray!

**Comment by jpurcell** [comment]
That's great! I'll be sure to add this in v1.0!
